spring:
  application:
    name: ShareCutter

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/sharecutter}
    username: ${SPRING_DATASOURCE_USERNAME:sharecutter}
    password: ${SPRING_DATASOURCE_PASSWORD:change-me-locally}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}
